-- ============================================================
-- Manual de uso — contenido editable desde el dashboard
-- ============================================================
-- Reemplaza el localStorage ("rm-manual-content-v2") por tablas reales.
-- Correr entero, una sola vez, en el SQL editor de Supabase.

-- ------------------------------------------------------------
-- 1. Tablas
-- ------------------------------------------------------------

create table if not exists public.manual_capitulos (
  id           bigint generated by default as identity primary key,
  orden        integer      not null default 1,
  eyebrow      text,
  titulo       text         not null default '',
  resumen      text,
  -- URL pública de la captura: del bucket "manual" o un asset estático (/manual/...)
  imagen_url   text,
  -- Ruta dentro del bucket. null cuando imagen_url es un asset estático del repo.
  imagen_path  text,
  created_at   timestamptz  not null default now(),
  updated_at   timestamptz  not null default now()
);

create table if not exists public.manual_pasos (
  id           bigint generated by default as identity primary key,
  capitulo_id  bigint       not null references public.manual_capitulos(id) on delete cascade,
  orden        integer      not null default 1,
  titulo       text         not null default '',
  texto        text         not null default '',
  created_at   timestamptz  not null default now()
);

create index if not exists manual_capitulos_orden_idx on public.manual_capitulos (orden);
create index if not exists manual_pasos_capitulo_idx  on public.manual_pasos (capitulo_id, orden);

-- updated_at automático en capítulos
create or replace function public.manual_capitulos_touch()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists manual_capitulos_touch_trg on public.manual_capitulos;
create trigger manual_capitulos_touch_trg
  before update on public.manual_capitulos
  for each row execute function public.manual_capitulos_touch();

-- ------------------------------------------------------------
-- 2. Contenido inicial (los 4 capítulos actuales)
-- ------------------------------------------------------------
-- Solo siembra si la tabla está vacía, para no duplicar en re-ejecuciones.

do $$
declare
  cap_id bigint;
begin
  if exists (select 1 from public.manual_capitulos) then
    raise notice 'manual_capitulos ya tiene datos: se omite el seed';
    return;
  end if;

  -- 01
  insert into public.manual_capitulos (orden, eyebrow, titulo, resumen, imagen_url)
  values (1, '01 · Primer ingreso', 'Entrar a tu perfil',
          'Usá el link que te compartió tu profesor para abrir tu espacio personal.',
          '/manual/manual1.png')
  returning id into cap_id;

  insert into public.manual_pasos (capitulo_id, orden, titulo, texto) values
    (cap_id, 1, 'Abrí el link',        'Entrá al link del Portal de Alumnos desde tu celular o computadora.'),
    (cap_id, 2, 'Ingresá con Gmail',   'Tocá Ingresar con Gmail y elegí la misma cuenta de correo que le diste a tu profesor.'),
    (cap_id, 3, 'Revisá tu perfil',    'Al entrar vas a ver tu nombre, modalidad, días de entrenamiento y el estado de tu membresía.');

  -- 02
  insert into public.manual_capitulos (orden, eyebrow, titulo, resumen, imagen_url)
  values (2, '02 · Tu rutina', 'Abrir tu planificación',
          'Desde Mi plan app encontrás todos los ejercicios que tu profesor preparó para vos.',
          '/manual/manual2.png')
  returning id into cap_id;

  insert into public.manual_pasos (capitulo_id, orden, titulo, texto) values
    (cap_id, 1, 'Entrá en Mi plan app', 'Desde tu perfil tocá Mi plan app. Si no aparece una rutina, avisale a tu profesor.'),
    (cap_id, 2, 'Elegí el día',         'Seleccioná el día que vas a entrenar y luego la semana correspondiente.'),
    (cap_id, 3, 'Leé cada ejercicio',   'Revisá el nombre, las series, la dosis, el RPE y las notas antes de empezar.');

  -- 03
  insert into public.manual_capitulos (orden, eyebrow, titulo, resumen, imagen_url)
  values (3, '03 · Durante el entrenamiento', 'Completar un ejercicio',
          'Cargá lo que hiciste en cada serie para que tu profesor pueda seguir tu progreso.',
          '/manual/manual3.png')
  returning id into cap_id;

  insert into public.manual_pasos (capitulo_id, orden, titulo, texto) values
    (cap_id, 1, 'Escribí tus datos',  'En cada serie cargá el peso, las repeticiones y el RPE si está indicado.'),
    (cap_id, 2, 'Guardá sin salir',   'Los datos se guardan automáticamente. Esperá el indicador Guardado antes de cerrar.'),
    (cap_id, 3, 'Agregá una nota',    'Si algo dolió, fue muy fácil o necesitaste adaptar el ejercicio, dejá una nota.');

  -- 04
  insert into public.manual_capitulos (orden, eyebrow, titulo, resumen, imagen_url)
  values (4, '04 · Tu historial', 'Calendario, progreso y salud',
          'Consultá tus entrenamientos anteriores y los documentos que tu equipo cargó para vos.',
          '/manual/manual4.png')
  returning id into cap_id;

  insert into public.manual_pasos (capitulo_id, orden, titulo, texto) values
    (cap_id, 1, 'Abrí el calendario',          'Usá el botón de calendario para ver qué días entrenaste y cuáles quedaron pendientes.'),
    (cap_id, 2, 'Revisá tu progreso',          'En el detalle podés comparar pesos, repeticiones y notas de semanas anteriores.'),
    (cap_id, 3, 'Antropometría y nutrición',   'Si tu profesor cargó mediciones, PDFs o hábitos, los vas a encontrar en la sección de salud de tu perfil.');
end $$;

-- ------------------------------------------------------------
-- 3. Bucket de imágenes
-- ------------------------------------------------------------
-- Público: las capturas se muestran con getPublicUrl(), sin URL firmada.

insert into storage.buckets (id, name, public)
values ('manual', 'manual', true)
on conflict (id) do update set public = true;

-- storage.objects sí tiene RLS activo, así que hacen falta políticas.
-- El frontend sube con la publishable key (rol anon), igual que antropometrías.

drop policy if exists "manual lectura publica"  on storage.objects;
drop policy if exists "manual subida"           on storage.objects;
drop policy if exists "manual actualizacion"    on storage.objects;
drop policy if exists "manual borrado"          on storage.objects;

create policy "manual lectura publica" on storage.objects
  for select using (bucket_id = 'manual');

create policy "manual subida" on storage.objects
  for insert with check (bucket_id = 'manual');

create policy "manual actualizacion" on storage.objects
  for update using (bucket_id = 'manual');

create policy "manual borrado" on storage.objects
  for delete using (bucket_id = 'manual');
